// The pipeline manifest: everything the recording pass discovers about
// one pipeline binary — published on every worker start, shown by the
// CLI/UI before any run exists.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/manifest/v1/manifest.proto

package manifestpb

import (
	schemapb "github.com/gopherex/schemapb/go/schemapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PipelineId string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	// Params/Result are gopherex schemapb schemas: the runtime
	// form/validation descriptor a UI renders and validates against
	// (four-language consumers, CEL rules).
	ParamsSchema *schemapb.Schema `protobuf:"bytes,2,opt,name=params_schema,json=paramsSchema,proto3" json:"params_schema,omitempty"`
	ResultSchema *schemapb.Schema `protobuf:"bytes,3,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	// Activities discovered by the recording pass (wire names, sorted).
	Activities []string `protobuf:"bytes,4,rep,name=activities,proto3" json:"activities,omitempty"`
	// Kinds are the entity kinds the pipeline's libraries declare.
	Kinds []string `protobuf:"bytes,5,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// Triggers declared on the pipeline; the server applies them on
	// publish — the code is the source of truth, a removed trigger is
	// unapplied by the next push.
	Triggers []*Trigger `protobuf:"bytes,6,rep,name=triggers,proto3" json:"triggers,omitempty"`
	// Concurrency policy for AUTOMATIC starts: "queue" (default),
	// "cancel-previous", "parallel".
	Concurrency string `protobuf:"bytes,7,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// Graph is the plan of the optimistic zero path.
	Graph *Graph `protobuf:"bytes,8,opt,name=graph,proto3" json:"graph,omitempty"`
	// KindDecls describe the brought kinds fully — the dictionary entry
	// material: what a declaration looks like, which commands the kind
	// answers, which observation dimensions it serves. `kinds` stays the
	// quick name list; an entry here always has a name there.
	KindDecls     []*KindDecl `protobuf:"bytes,9,rep,name=kind_decls,json=kindDecls,proto3" json:"kind_decls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_proto_manifest_v1_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *Manifest) GetParamsSchema() *schemapb.Schema {
	if x != nil {
		return x.ParamsSchema
	}
	return nil
}

func (x *Manifest) GetResultSchema() *schemapb.Schema {
	if x != nil {
		return x.ResultSchema
	}
	return nil
}

func (x *Manifest) GetActivities() []string {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *Manifest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Manifest) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *Manifest) GetConcurrency() string {
	if x != nil {
		return x.Concurrency
	}
	return ""
}

func (x *Manifest) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *Manifest) GetKindDecls() []*KindDecl {
	if x != nil {
		return x.KindDecls
	}
	return nil
}

// KindDecl is one brought kind, described the way the installation's
// dictionary wants it.
type KindDecl struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// SpecSchema is the declaration's schema.
	SpecSchema *schemapb.Schema    `protobuf:"bytes,3,opt,name=spec_schema,json=specSchema,proto3" json:"spec_schema,omitempty"`
	Commands   []*KindDecl_Command `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	// Dimensions: state, events, logs, metrics, traces.
	Dimensions    []string `protobuf:"bytes,5,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindDecl) Reset() {
	*x = KindDecl{}
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindDecl) ProtoMessage() {}

func (x *KindDecl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindDecl.ProtoReflect.Descriptor instead.
func (*KindDecl) Descriptor() ([]byte, []int) {
	return file_proto_manifest_v1_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *KindDecl) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KindDecl) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KindDecl) GetSpecSchema() *schemapb.Schema {
	if x != nil {
		return x.SpecSchema
	}
	return nil
}

func (x *KindDecl) GetCommands() []*KindDecl_Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *KindDecl) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

// Graph is the pipeline's PLAN: what the recording pass saw walking
// the OPTIMISTIC ZERO PATH once — declared resources with their tree
// edges and the ordered steps with their data dependencies. Branches
// on runtime values are invisible by construction: this is the shape
// of the honest common path, not an execution guarantee.
type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Steps         []*GraphStep           `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_proto_manifest_v1_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *Graph) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Graph) GetSteps() []*GraphStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type GraphNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ref addresses the declared resource ("kind/id").
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Parent is the declared owner; empty means the run.
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Children are existing resources the declaration claims.
	Children      []string `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_proto_manifest_v1_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *GraphNode) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GraphNode) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *GraphNode) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

type GraphStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Op: "declare" | "activity" | "activity-all" | "attach" | "transfer".
	Op string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	// Subject: the resource ref or the activity name.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Agent executing an activity ("agent/x", or "<selection>" for a
	// fan-out).
	Agent string `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	// Note: the guarantee ("at-most-once"), the transfer target, ...
	Note string `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	// Deps are resources whose Ready output fed this step.
	Deps          []string `protobuf:"bytes,5,rep,name=deps,proto3" json:"deps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphStep) Reset() {
	*x = GraphStep{}
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStep) ProtoMessage() {}

func (x *GraphStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStep.ProtoReflect.Descriptor instead.
func (*GraphStep) Descriptor() ([]byte, []int) {
	return file_proto_manifest_v1_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *GraphStep) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *GraphStep) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GraphStep) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *GraphStep) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GraphStep) GetDeps() []string {
	if x != nil {
		return x.Deps
	}
	return nil
}

type Trigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind: "cron" | "webhook".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name identifies the trigger; webhooks are addressed by it
	// (/hooks/{ns}/{pipeline}/{name}). Crons name their history events.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Spec is the cron expression (cron only).
	Spec string `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// SecretName names the HMAC/token secret in the installation's store
	// (webhook only).
	SecretName string `protobuf:"bytes,4,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	// Params is the fixed typed-params JSON this trigger starts runs
	// with; a webhook's request body lands in the reserved "event" field
	// on top.
	Params        []byte `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_proto_manifest_v1_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *Trigger) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Trigger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trigger) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *Trigger) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *Trigger) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type KindDecl_Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PayloadSchema *schemapb.Schema       `protobuf:"bytes,2,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindDecl_Command) Reset() {
	*x = KindDecl_Command{}
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindDecl_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindDecl_Command) ProtoMessage() {}

func (x *KindDecl_Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manifest_v1_manifest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindDecl_Command.ProtoReflect.Descriptor instead.
func (*KindDecl_Command) Descriptor() ([]byte, []int) {
	return file_proto_manifest_v1_manifest_proto_rawDescGZIP(), []int{1, 0}
}

func (x *KindDecl_Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KindDecl_Command) GetPayloadSchema() *schemapb.Schema {
	if x != nil {
		return x.PayloadSchema
	}
	return nil
}

var File_proto_manifest_v1_manifest_proto protoreflect.FileDescriptor

const file_proto_manifest_v1_manifest_proto_rawDesc = "" +
	"\n" +
	" proto/manifest/v1/manifest.proto\x12\x14graphene.manifest.v1\x1a\x15schemapb/schema.proto\"\x9e\x03\n" +
	"\bManifest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x125\n" +
	"\rparams_schema\x18\x02 \x01(\v2\x10.schemapb.SchemaR\fparamsSchema\x125\n" +
	"\rresult_schema\x18\x03 \x01(\v2\x10.schemapb.SchemaR\fresultSchema\x12\x1e\n" +
	"\n" +
	"activities\x18\x04 \x03(\tR\n" +
	"activities\x12\x14\n" +
	"\x05kinds\x18\x05 \x03(\tR\x05kinds\x129\n" +
	"\btriggers\x18\x06 \x03(\v2\x1d.graphene.manifest.v1.TriggerR\btriggers\x12 \n" +
	"\vconcurrency\x18\a \x01(\tR\vconcurrency\x121\n" +
	"\x05graph\x18\b \x01(\v2\x1b.graphene.manifest.v1.GraphR\x05graph\x12=\n" +
	"\n" +
	"kind_decls\x18\t \x03(\v2\x1e.graphene.manifest.v1.KindDeclR\tkindDecls\"\xaf\x02\n" +
	"\bKindDecl\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\vspec_schema\x18\x03 \x01(\v2\x10.schemapb.SchemaR\n" +
	"specSchema\x12B\n" +
	"\bcommands\x18\x04 \x03(\v2&.graphene.manifest.v1.KindDecl.CommandR\bcommands\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x05 \x03(\tR\n" +
	"dimensions\x1aV\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x0epayload_schema\x18\x02 \x01(\v2\x10.schemapb.SchemaR\rpayloadSchema\"u\n" +
	"\x05Graph\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.graphene.manifest.v1.GraphNodeR\x05nodes\x125\n" +
	"\x05steps\x18\x02 \x03(\v2\x1f.graphene.manifest.v1.GraphStepR\x05steps\"Q\n" +
	"\tGraphNode\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12\x1a\n" +
	"\bchildren\x18\x03 \x03(\tR\bchildren\"s\n" +
	"\tGraphStep\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05agent\x18\x03 \x01(\tR\x05agent\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x12\n" +
	"\x04deps\x18\x05 \x03(\tR\x04deps\"~\n" +
	"\aTrigger\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\tR\x04spec\x12\x1f\n" +
	"\vsecret_name\x18\x04 \x01(\tR\n" +
	"secretName\x12\x16\n" +
	"\x06params\x18\x05 \x01(\fR\x06paramsBBZ@github.com/graphene-ci/pipeline/pkg/proto/manifest/v1;manifestpbb\x06proto3"

var (
	file_proto_manifest_v1_manifest_proto_rawDescOnce sync.Once
	file_proto_manifest_v1_manifest_proto_rawDescData []byte
)

func file_proto_manifest_v1_manifest_proto_rawDescGZIP() []byte {
	file_proto_manifest_v1_manifest_proto_rawDescOnce.Do(func() {
		file_proto_manifest_v1_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manifest_v1_manifest_proto_rawDesc), len(file_proto_manifest_v1_manifest_proto_rawDesc)))
	})
	return file_proto_manifest_v1_manifest_proto_rawDescData
}

var file_proto_manifest_v1_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_manifest_v1_manifest_proto_goTypes = []any{
	(*Manifest)(nil),         // 0: graphene.manifest.v1.Manifest
	(*KindDecl)(nil),         // 1: graphene.manifest.v1.KindDecl
	(*Graph)(nil),            // 2: graphene.manifest.v1.Graph
	(*GraphNode)(nil),        // 3: graphene.manifest.v1.GraphNode
	(*GraphStep)(nil),        // 4: graphene.manifest.v1.GraphStep
	(*Trigger)(nil),          // 5: graphene.manifest.v1.Trigger
	(*KindDecl_Command)(nil), // 6: graphene.manifest.v1.KindDecl.Command
	(*schemapb.Schema)(nil),  // 7: schemapb.Schema
}
var file_proto_manifest_v1_manifest_proto_depIdxs = []int32{
	7,  // 0: graphene.manifest.v1.Manifest.params_schema:type_name -> schemapb.Schema
	7,  // 1: graphene.manifest.v1.Manifest.result_schema:type_name -> schemapb.Schema
	5,  // 2: graphene.manifest.v1.Manifest.triggers:type_name -> graphene.manifest.v1.Trigger
	2,  // 3: graphene.manifest.v1.Manifest.graph:type_name -> graphene.manifest.v1.Graph
	1,  // 4: graphene.manifest.v1.Manifest.kind_decls:type_name -> graphene.manifest.v1.KindDecl
	7,  // 5: graphene.manifest.v1.KindDecl.spec_schema:type_name -> schemapb.Schema
	6,  // 6: graphene.manifest.v1.KindDecl.commands:type_name -> graphene.manifest.v1.KindDecl.Command
	3,  // 7: graphene.manifest.v1.Graph.nodes:type_name -> graphene.manifest.v1.GraphNode
	4,  // 8: graphene.manifest.v1.Graph.steps:type_name -> graphene.manifest.v1.GraphStep
	7,  // 9: graphene.manifest.v1.KindDecl.Command.payload_schema:type_name -> schemapb.Schema
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_manifest_v1_manifest_proto_init() }
func file_proto_manifest_v1_manifest_proto_init() {
	if File_proto_manifest_v1_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manifest_v1_manifest_proto_rawDesc), len(file_proto_manifest_v1_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_manifest_v1_manifest_proto_goTypes,
		DependencyIndexes: file_proto_manifest_v1_manifest_proto_depIdxs,
		MessageInfos:      file_proto_manifest_v1_manifest_proto_msgTypes,
	}.Build()
	File_proto_manifest_v1_manifest_proto = out.File
	file_proto_manifest_v1_manifest_proto_goTypes = nil
	file_proto_manifest_v1_manifest_proto_depIdxs = nil
}
