// Worker plane: what the RUNNING USER CODE calls — secrets at the point
// of use, capabilities from where they were installed, blob bytes. The
// namespace comes from the worker's token; a worker cannot ask for
// another namespace's anything. The contract lives in the pipeline
// repository — the worker side owns it; the server imports and serves.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/workerplane/v1/workerplane.proto

package workerplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version is informative; matching is by label equality only.
	Version string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Labels  map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// BroughtBy is free text: an installer, a person, an image.
	BroughtBy     string `protobuf:"bytes,4,opt,name=brought_by,json=broughtBy,proto3" json:"brought_by,omitempty"`
	Ready         bool   `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{2}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capability) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Capability) GetBroughtBy() string {
	if x != nil {
		return x.BroughtBy
	}
	return ""
}

func (x *Capability) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type PublishCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capability    *Capability            `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCapabilityRequest) Reset() {
	*x = PublishCapabilityRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCapabilityRequest) ProtoMessage() {}

func (x *PublishCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCapabilityRequest.ProtoReflect.Descriptor instead.
func (*PublishCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{3}
}

func (x *PublishCapabilityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PublishCapabilityRequest) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type PublishCapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCapabilityResponse) Reset() {
	*x = PublishCapabilityResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCapabilityResponse) ProtoMessage() {}

func (x *PublishCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCapabilityResponse.ProtoReflect.Descriptor instead.
func (*PublishCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{4}
}

type PutBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunks of the blob, in order.
	Chunk         []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobRequest) Reset() {
	*x = PutBlobRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobRequest) ProtoMessage() {}

func (x *PutBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobRequest.ProtoReflect.Descriptor instead.
func (*PutBlobRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{5}
}

func (x *PutBlobRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutBlobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest is "sha256:<hex>"; Location addresses the bytes in the store.
	Digest        string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Location      string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Size          int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobResponse) Reset() {
	*x = PutBlobResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobResponse) ProtoMessage() {}

func (x *PutBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobResponse.ProtoReflect.Descriptor instead.
func (*PutBlobResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{6}
}

func (x *PutBlobResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PutBlobResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PutBlobResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRequest) Reset() {
	*x = GetBlobRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRequest) ProtoMessage() {}

func (x *GetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlobRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GetBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobResponse) Reset() {
	*x = GetBlobResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobResponse) ProtoMessage() {}

func (x *GetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobResponse.ProtoReflect.Descriptor instead.
func (*GetBlobResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlobResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type EmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ref addresses the entity ("kind/id").
	Ref  string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Payload is the event's body as JSON.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{9}
}

func (x *EmitRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *EmitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmitRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{10}
}

type PublishManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Manifest is graphene.manifest.v1.Manifest as protojson — kept as
	// bytes so the worker plane needs no cross-file proto import.
	Manifest []byte `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// Image, when set, records the worker image this manifest was
	// published from — a push sets it; a worker start leaves it empty to
	// keep the record's current image.
	Image         string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishManifestRequest) Reset() {
	*x = PublishManifestRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishManifestRequest) ProtoMessage() {}

func (x *PublishManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishManifestRequest.ProtoReflect.Descriptor instead.
func (*PublishManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{11}
}

func (x *PublishManifestRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *PublishManifestRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type PublishManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishManifestResponse) Reset() {
	*x = PublishManifestResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishManifestResponse) ProtoMessage() {}

func (x *PublishManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishManifestResponse.ProtoReflect.Descriptor instead.
func (*PublishManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{12}
}

type GetPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRequest) Reset() {
	*x = GetPipelineRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRequest) ProtoMessage() {}

func (x *GetPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{13}
}

func (x *GetPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type GetPipelineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image is the current worker image of the pipeline; empty when the
	// pipeline was never pushed.
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Manifest is the last published manifest as protojson.
	Manifest      []byte `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Digest        string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineResponse) Reset() {
	*x = GetPipelineResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineResponse) ProtoMessage() {}

func (x *GetPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{14}
}

func (x *GetPipelineResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetPipelineResponse) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *GetPipelineResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type WatchRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRunRequest) Reset() {
	*x = WatchRunRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunRequest) ProtoMessage() {}

func (x *WatchRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunRequest.ProtoReflect.Descriptor instead.
func (*WatchRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{15}
}

func (x *WatchRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type WatchRunEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRunEvent) Reset() {
	*x = WatchRunEvent{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunEvent) ProtoMessage() {}

func (x *WatchRunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunEvent.ProtoReflect.Descriptor instead.
func (*WatchRunEvent) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{16}
}

func (x *WatchRunEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Pipeline is the workflow type on the wire — the pipeline id.
	Pipeline string `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// Params is the typed params value of the pipeline, as JSON.
	Params []byte `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	// Image makes the run MANAGED: the server launches the worker
	// container itself.
	Image         string            `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{17}
}

func (x *StartRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartRunRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *StartRunRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *StartRunRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartRunRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type StartRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TemporalRunId string                 `protobuf:"bytes,2,opt,name=temporal_run_id,json=temporalRunId,proto3" json:"temporal_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunResponse) Reset() {
	*x = StartRunResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunResponse) ProtoMessage() {}

func (x *StartRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunResponse.ProtoReflect.Descriptor instead.
func (*StartRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{18}
}

func (x *StartRunResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartRunResponse) GetTemporalRunId() string {
	if x != nil {
		return x.TemporalRunId
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{19}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResponse) Reset() {
	*x = GetRunResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResponse) ProtoMessage() {}

func (x *GetRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResponse.ProtoReflect.Descriptor instead.
func (*GetRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{20}
}

func (x *GetRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RunResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResultRequest) Reset() {
	*x = RunResultRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResultRequest) ProtoMessage() {}

func (x *RunResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResultRequest.ProtoReflect.Descriptor instead.
func (*RunResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{21}
}

func (x *RunResultRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result is the run's typed Result as JSON.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResultResponse) Reset() {
	*x = RunResultResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResultResponse) ProtoMessage() {}

func (x *RunResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResultResponse.ProtoReflect.Descriptor instead.
func (*RunResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{22}
}

func (x *RunResultResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_workerplane_v1_workerplane_proto protoreflect.FileDescriptor

const file_proto_workerplane_v1_workerplane_proto_rawDesc = "" +
	"\n" +
	"&proto/workerplane/v1/workerplane.proto\x12\x17graphene.workerplane.v1\"&\n" +
	"\x10GetSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x11GetSecretResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xf3\x01\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12G\n" +
	"\x06labels\x18\x03 \x03(\v2/.graphene.workerplane.v1.Capability.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"brought_by\x18\x04 \x01(\tR\tbroughtBy\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x18PublishCapabilityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12C\n" +
	"\n" +
	"capability\x18\x02 \x01(\v2#.graphene.workerplane.v1.CapabilityR\n" +
	"capability\"\x1b\n" +
	"\x19PublishCapabilityResponse\"&\n" +
	"\x0ePutBlobRequest\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"Y\n" +
	"\x0fPutBlobResponse\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\",\n" +
	"\x0eGetBlobRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"'\n" +
	"\x0fGetBlobResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"M\n" +
	"\vEmitRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x0e\n" +
	"\fEmitResponse\"J\n" +
	"\x16PublishManifestRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\x19\n" +
	"\x17PublishManifestResponse\"5\n" +
	"\x12GetPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"_\n" +
	"\x13GetPipelineResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1a\n" +
	"\bmanifest\x18\x02 \x01(\fR\bmanifest\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\"(\n" +
	"\x0fWatchRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"'\n" +
	"\rWatchRunEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xfb\x01\n" +
	"\x0fStartRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bpipeline\x18\x02 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12L\n" +
	"\x06labels\x18\x05 \x03(\v24.graphene.workerplane.v1.StartRunRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x10StartRunResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12&\n" +
	"\x0ftemporal_run_id\x18\x02 \x01(\tR\rtemporalRunId\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"(\n" +
	"\x0eGetRunResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\")\n" +
	"\x10RunResultRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"+\n" +
	"\x11RunResultResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2p\n" +
	"\n" +
	"SecretsAPI\x12b\n" +
	"\tGetSecret\x12).graphene.workerplane.v1.GetSecretRequest\x1a*.graphene.workerplane.v1.GetSecretResponse2\x8d\x01\n" +
	"\x0fCapabilitiesAPI\x12z\n" +
	"\x11PublishCapability\x121.graphene.workerplane.v1.PublishCapabilityRequest\x1a2.graphene.workerplane.v1.PublishCapabilityResponse2\xca\x01\n" +
	"\bBlobsAPI\x12^\n" +
	"\aPutBlob\x12'.graphene.workerplane.v1.PutBlobRequest\x1a(.graphene.workerplane.v1.PutBlobResponse(\x01\x12^\n" +
	"\aGetBlob\x12'.graphene.workerplane.v1.GetBlobRequest\x1a(.graphene.workerplane.v1.GetBlobResponse0\x012`\n" +
	"\tEventsAPI\x12S\n" +
	"\x04Emit\x12$.graphene.workerplane.v1.EmitRequest\x1a%.graphene.workerplane.v1.EmitResponse2\xed\x01\n" +
	"\vManifestAPI\x12t\n" +
	"\x0fPublishManifest\x12/.graphene.workerplane.v1.PublishManifestRequest\x1a0.graphene.workerplane.v1.PublishManifestResponse\x12h\n" +
	"\vGetPipeline\x12+.graphene.workerplane.v1.GetPipelineRequest\x1a,.graphene.workerplane.v1.GetPipelineResponse2\x89\x03\n" +
	"\aRunsAPI\x12_\n" +
	"\bStartRun\x12(.graphene.workerplane.v1.StartRunRequest\x1a).graphene.workerplane.v1.StartRunResponse\x12Y\n" +
	"\x06GetRun\x12&.graphene.workerplane.v1.GetRunRequest\x1a'.graphene.workerplane.v1.GetRunResponse\x12^\n" +
	"\bWatchRun\x12(.graphene.workerplane.v1.WatchRunRequest\x1a&.graphene.workerplane.v1.WatchRunEvent0\x01\x12b\n" +
	"\tRunResult\x12).graphene.workerplane.v1.RunResultRequest\x1a*.graphene.workerplane.v1.RunResultResponseBHZFgithub.com/graphene-ci/pipeline/pkg/proto/workerplane/v1;workerplanev1b\x06proto3"

var (
	file_proto_workerplane_v1_workerplane_proto_rawDescOnce sync.Once
	file_proto_workerplane_v1_workerplane_proto_rawDescData []byte
)

func file_proto_workerplane_v1_workerplane_proto_rawDescGZIP() []byte {
	file_proto_workerplane_v1_workerplane_proto_rawDescOnce.Do(func() {
		file_proto_workerplane_v1_workerplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workerplane_v1_workerplane_proto_rawDesc), len(file_proto_workerplane_v1_workerplane_proto_rawDesc)))
	})
	return file_proto_workerplane_v1_workerplane_proto_rawDescData
}

var file_proto_workerplane_v1_workerplane_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_workerplane_v1_workerplane_proto_goTypes = []any{
	(*GetSecretRequest)(nil),          // 0: graphene.workerplane.v1.GetSecretRequest
	(*GetSecretResponse)(nil),         // 1: graphene.workerplane.v1.GetSecretResponse
	(*Capability)(nil),                // 2: graphene.workerplane.v1.Capability
	(*PublishCapabilityRequest)(nil),  // 3: graphene.workerplane.v1.PublishCapabilityRequest
	(*PublishCapabilityResponse)(nil), // 4: graphene.workerplane.v1.PublishCapabilityResponse
	(*PutBlobRequest)(nil),            // 5: graphene.workerplane.v1.PutBlobRequest
	(*PutBlobResponse)(nil),           // 6: graphene.workerplane.v1.PutBlobResponse
	(*GetBlobRequest)(nil),            // 7: graphene.workerplane.v1.GetBlobRequest
	(*GetBlobResponse)(nil),           // 8: graphene.workerplane.v1.GetBlobResponse
	(*EmitRequest)(nil),               // 9: graphene.workerplane.v1.EmitRequest
	(*EmitResponse)(nil),              // 10: graphene.workerplane.v1.EmitResponse
	(*PublishManifestRequest)(nil),    // 11: graphene.workerplane.v1.PublishManifestRequest
	(*PublishManifestResponse)(nil),   // 12: graphene.workerplane.v1.PublishManifestResponse
	(*GetPipelineRequest)(nil),        // 13: graphene.workerplane.v1.GetPipelineRequest
	(*GetPipelineResponse)(nil),       // 14: graphene.workerplane.v1.GetPipelineResponse
	(*WatchRunRequest)(nil),           // 15: graphene.workerplane.v1.WatchRunRequest
	(*WatchRunEvent)(nil),             // 16: graphene.workerplane.v1.WatchRunEvent
	(*StartRunRequest)(nil),           // 17: graphene.workerplane.v1.StartRunRequest
	(*StartRunResponse)(nil),          // 18: graphene.workerplane.v1.StartRunResponse
	(*GetRunRequest)(nil),             // 19: graphene.workerplane.v1.GetRunRequest
	(*GetRunResponse)(nil),            // 20: graphene.workerplane.v1.GetRunResponse
	(*RunResultRequest)(nil),          // 21: graphene.workerplane.v1.RunResultRequest
	(*RunResultResponse)(nil),         // 22: graphene.workerplane.v1.RunResultResponse
	nil,                               // 23: graphene.workerplane.v1.Capability.LabelsEntry
	nil,                               // 24: graphene.workerplane.v1.StartRunRequest.LabelsEntry
}
var file_proto_workerplane_v1_workerplane_proto_depIdxs = []int32{
	23, // 0: graphene.workerplane.v1.Capability.labels:type_name -> graphene.workerplane.v1.Capability.LabelsEntry
	2,  // 1: graphene.workerplane.v1.PublishCapabilityRequest.capability:type_name -> graphene.workerplane.v1.Capability
	24, // 2: graphene.workerplane.v1.StartRunRequest.labels:type_name -> graphene.workerplane.v1.StartRunRequest.LabelsEntry
	0,  // 3: graphene.workerplane.v1.SecretsAPI.GetSecret:input_type -> graphene.workerplane.v1.GetSecretRequest
	3,  // 4: graphene.workerplane.v1.CapabilitiesAPI.PublishCapability:input_type -> graphene.workerplane.v1.PublishCapabilityRequest
	5,  // 5: graphene.workerplane.v1.BlobsAPI.PutBlob:input_type -> graphene.workerplane.v1.PutBlobRequest
	7,  // 6: graphene.workerplane.v1.BlobsAPI.GetBlob:input_type -> graphene.workerplane.v1.GetBlobRequest
	9,  // 7: graphene.workerplane.v1.EventsAPI.Emit:input_type -> graphene.workerplane.v1.EmitRequest
	11, // 8: graphene.workerplane.v1.ManifestAPI.PublishManifest:input_type -> graphene.workerplane.v1.PublishManifestRequest
	13, // 9: graphene.workerplane.v1.ManifestAPI.GetPipeline:input_type -> graphene.workerplane.v1.GetPipelineRequest
	17, // 10: graphene.workerplane.v1.RunsAPI.StartRun:input_type -> graphene.workerplane.v1.StartRunRequest
	19, // 11: graphene.workerplane.v1.RunsAPI.GetRun:input_type -> graphene.workerplane.v1.GetRunRequest
	15, // 12: graphene.workerplane.v1.RunsAPI.WatchRun:input_type -> graphene.workerplane.v1.WatchRunRequest
	21, // 13: graphene.workerplane.v1.RunsAPI.RunResult:input_type -> graphene.workerplane.v1.RunResultRequest
	1,  // 14: graphene.workerplane.v1.SecretsAPI.GetSecret:output_type -> graphene.workerplane.v1.GetSecretResponse
	4,  // 15: graphene.workerplane.v1.CapabilitiesAPI.PublishCapability:output_type -> graphene.workerplane.v1.PublishCapabilityResponse
	6,  // 16: graphene.workerplane.v1.BlobsAPI.PutBlob:output_type -> graphene.workerplane.v1.PutBlobResponse
	8,  // 17: graphene.workerplane.v1.BlobsAPI.GetBlob:output_type -> graphene.workerplane.v1.GetBlobResponse
	10, // 18: graphene.workerplane.v1.EventsAPI.Emit:output_type -> graphene.workerplane.v1.EmitResponse
	12, // 19: graphene.workerplane.v1.ManifestAPI.PublishManifest:output_type -> graphene.workerplane.v1.PublishManifestResponse
	14, // 20: graphene.workerplane.v1.ManifestAPI.GetPipeline:output_type -> graphene.workerplane.v1.GetPipelineResponse
	18, // 21: graphene.workerplane.v1.RunsAPI.StartRun:output_type -> graphene.workerplane.v1.StartRunResponse
	20, // 22: graphene.workerplane.v1.RunsAPI.GetRun:output_type -> graphene.workerplane.v1.GetRunResponse
	16, // 23: graphene.workerplane.v1.RunsAPI.WatchRun:output_type -> graphene.workerplane.v1.WatchRunEvent
	22, // 24: graphene.workerplane.v1.RunsAPI.RunResult:output_type -> graphene.workerplane.v1.RunResultResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_workerplane_v1_workerplane_proto_init() }
func file_proto_workerplane_v1_workerplane_proto_init() {
	if File_proto_workerplane_v1_workerplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workerplane_v1_workerplane_proto_rawDesc), len(file_proto_workerplane_v1_workerplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_proto_workerplane_v1_workerplane_proto_goTypes,
		DependencyIndexes: file_proto_workerplane_v1_workerplane_proto_depIdxs,
		MessageInfos:      file_proto_workerplane_v1_workerplane_proto_msgTypes,
	}.Build()
	File_proto_workerplane_v1_workerplane_proto = out.File
	file_proto_workerplane_v1_workerplane_proto_goTypes = nil
	file_proto_workerplane_v1_workerplane_proto_depIdxs = nil
}
