// Worker plane: what the RUNNING USER CODE calls — secrets at the point
// of use, capabilities from where they were installed, blob bytes. The
// namespace comes from the worker's token; a worker cannot ask for
// another namespace's anything. The contract lives in the pipeline
// repository — the worker side owns it; the server imports and serves.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/workerplane/v1/workerplane.proto

package workerplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsAPI_GetSecret_FullMethodName = "/graphene.workerplane.v1.SecretsAPI/GetSecret"
)

// SecretsAPIClient is the client API for SecretsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretsAPI resolves secret names to values — exactly once, at the
// point of use; the value never travels back into records.
type SecretsAPIClient interface {
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
}

type secretsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsAPIClient(cc grpc.ClientConnInterface) SecretsAPIClient {
	return &secretsAPIClient{cc}
}

func (c *secretsAPIClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, SecretsAPI_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsAPIServer is the server API for SecretsAPI service.
// All implementations must embed UnimplementedSecretsAPIServer
// for forward compatibility.
//
// SecretsAPI resolves secret names to values — exactly once, at the
// point of use; the value never travels back into records.
type SecretsAPIServer interface {
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	mustEmbedUnimplementedSecretsAPIServer()
}

// UnimplementedSecretsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsAPIServer struct{}

func (UnimplementedSecretsAPIServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedSecretsAPIServer) mustEmbedUnimplementedSecretsAPIServer() {}
func (UnimplementedSecretsAPIServer) testEmbeddedByValue()                    {}

// UnsafeSecretsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsAPIServer will
// result in compilation errors.
type UnsafeSecretsAPIServer interface {
	mustEmbedUnimplementedSecretsAPIServer()
}

func RegisterSecretsAPIServer(s grpc.ServiceRegistrar, srv SecretsAPIServer) {
	// If the following call panics, it indicates UnimplementedSecretsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsAPI_ServiceDesc, srv)
}

func _SecretsAPI_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsAPIServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsAPI_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsAPIServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsAPI_ServiceDesc is the grpc.ServiceDesc for SecretsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.workerplane.v1.SecretsAPI",
	HandlerType: (*SecretsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _SecretsAPI_GetSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workerplane/v1/workerplane.proto",
}

const (
	CapabilitiesAPI_PublishCapability_FullMethodName = "/graphene.workerplane.v1.CapabilitiesAPI/PublishCapability"
)

// CapabilitiesAPIClient is the client API for CapabilitiesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapabilitiesAPI publishes what a machine now CAN — written down where
// the installation happened.
type CapabilitiesAPIClient interface {
	PublishCapability(ctx context.Context, in *PublishCapabilityRequest, opts ...grpc.CallOption) (*PublishCapabilityResponse, error)
}

type capabilitiesAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilitiesAPIClient(cc grpc.ClientConnInterface) CapabilitiesAPIClient {
	return &capabilitiesAPIClient{cc}
}

func (c *capabilitiesAPIClient) PublishCapability(ctx context.Context, in *PublishCapabilityRequest, opts ...grpc.CallOption) (*PublishCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishCapabilityResponse)
	err := c.cc.Invoke(ctx, CapabilitiesAPI_PublishCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilitiesAPIServer is the server API for CapabilitiesAPI service.
// All implementations must embed UnimplementedCapabilitiesAPIServer
// for forward compatibility.
//
// CapabilitiesAPI publishes what a machine now CAN — written down where
// the installation happened.
type CapabilitiesAPIServer interface {
	PublishCapability(context.Context, *PublishCapabilityRequest) (*PublishCapabilityResponse, error)
	mustEmbedUnimplementedCapabilitiesAPIServer()
}

// UnimplementedCapabilitiesAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilitiesAPIServer struct{}

func (UnimplementedCapabilitiesAPIServer) PublishCapability(context.Context, *PublishCapabilityRequest) (*PublishCapabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishCapability not implemented")
}
func (UnimplementedCapabilitiesAPIServer) mustEmbedUnimplementedCapabilitiesAPIServer() {}
func (UnimplementedCapabilitiesAPIServer) testEmbeddedByValue()                         {}

// UnsafeCapabilitiesAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilitiesAPIServer will
// result in compilation errors.
type UnsafeCapabilitiesAPIServer interface {
	mustEmbedUnimplementedCapabilitiesAPIServer()
}

func RegisterCapabilitiesAPIServer(s grpc.ServiceRegistrar, srv CapabilitiesAPIServer) {
	// If the following call panics, it indicates UnimplementedCapabilitiesAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilitiesAPI_ServiceDesc, srv)
}

func _CapabilitiesAPI_PublishCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilitiesAPIServer).PublishCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilitiesAPI_PublishCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilitiesAPIServer).PublishCapability(ctx, req.(*PublishCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilitiesAPI_ServiceDesc is the grpc.ServiceDesc for CapabilitiesAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilitiesAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.workerplane.v1.CapabilitiesAPI",
	HandlerType: (*CapabilitiesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishCapability",
			Handler:    _CapabilitiesAPI_PublishCapability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workerplane/v1/workerplane.proto",
}

const (
	BlobsAPI_PutBlob_FullMethodName = "/graphene.workerplane.v1.BlobsAPI/PutBlob"
	BlobsAPI_GetBlob_FullMethodName = "/graphene.workerplane.v1.BlobsAPI/GetBlob"
)

// BlobsAPIClient is the client API for BlobsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlobsAPI moves artifact bytes. Content-addressed: the digest IS the
// location; a repeated Put of the same bytes is a no-op by construction.
type BlobsAPIClient interface {
	PutBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutBlobRequest, PutBlobResponse], error)
	GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBlobResponse], error)
}

type blobsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobsAPIClient(cc grpc.ClientConnInterface) BlobsAPIClient {
	return &blobsAPIClient{cc}
}

func (c *blobsAPIClient) PutBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutBlobRequest, PutBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobsAPI_ServiceDesc.Streams[0], BlobsAPI_PutBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutBlobRequest, PutBlobResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobsAPI_PutBlobClient = grpc.ClientStreamingClient[PutBlobRequest, PutBlobResponse]

func (c *blobsAPIClient) GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobsAPI_ServiceDesc.Streams[1], BlobsAPI_GetBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBlobRequest, GetBlobResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobsAPI_GetBlobClient = grpc.ServerStreamingClient[GetBlobResponse]

// BlobsAPIServer is the server API for BlobsAPI service.
// All implementations must embed UnimplementedBlobsAPIServer
// for forward compatibility.
//
// BlobsAPI moves artifact bytes. Content-addressed: the digest IS the
// location; a repeated Put of the same bytes is a no-op by construction.
type BlobsAPIServer interface {
	PutBlob(grpc.ClientStreamingServer[PutBlobRequest, PutBlobResponse]) error
	GetBlob(*GetBlobRequest, grpc.ServerStreamingServer[GetBlobResponse]) error
	mustEmbedUnimplementedBlobsAPIServer()
}

// UnimplementedBlobsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobsAPIServer struct{}

func (UnimplementedBlobsAPIServer) PutBlob(grpc.ClientStreamingServer[PutBlobRequest, PutBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method PutBlob not implemented")
}
func (UnimplementedBlobsAPIServer) GetBlob(*GetBlobRequest, grpc.ServerStreamingServer[GetBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method GetBlob not implemented")
}
func (UnimplementedBlobsAPIServer) mustEmbedUnimplementedBlobsAPIServer() {}
func (UnimplementedBlobsAPIServer) testEmbeddedByValue()                  {}

// UnsafeBlobsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobsAPIServer will
// result in compilation errors.
type UnsafeBlobsAPIServer interface {
	mustEmbedUnimplementedBlobsAPIServer()
}

func RegisterBlobsAPIServer(s grpc.ServiceRegistrar, srv BlobsAPIServer) {
	// If the following call panics, it indicates UnimplementedBlobsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlobsAPI_ServiceDesc, srv)
}

func _BlobsAPI_PutBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlobsAPIServer).PutBlob(&grpc.GenericServerStream[PutBlobRequest, PutBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobsAPI_PutBlobServer = grpc.ClientStreamingServer[PutBlobRequest, PutBlobResponse]

func _BlobsAPI_GetBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobsAPIServer).GetBlob(m, &grpc.GenericServerStream[GetBlobRequest, GetBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobsAPI_GetBlobServer = grpc.ServerStreamingServer[GetBlobResponse]

// BlobsAPI_ServiceDesc is the grpc.ServiceDesc for BlobsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.workerplane.v1.BlobsAPI",
	HandlerType: (*BlobsAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutBlob",
			Handler:       _BlobsAPI_PutBlob_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetBlob",
			Handler:       _BlobsAPI_GetBlob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/workerplane/v1/workerplane.proto",
}

const (
	EventsAPI_Emit_FullMethodName = "/graphene.workerplane.v1.EventsAPI/Emit"
)

// EventsAPIClient is the client API for EventsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventsAPI carries DOMAIN EVENTS into an entity's history — the plane
// of truth. A note is a milestone, not a log line: streams belong in
// telemetry.
type EventsAPIClient interface {
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error)
}

type eventsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsAPIClient(cc grpc.ClientConnInterface) EventsAPIClient {
	return &eventsAPIClient{cc}
}

func (c *eventsAPIClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, EventsAPI_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsAPIServer is the server API for EventsAPI service.
// All implementations must embed UnimplementedEventsAPIServer
// for forward compatibility.
//
// EventsAPI carries DOMAIN EVENTS into an entity's history — the plane
// of truth. A note is a milestone, not a log line: streams belong in
// telemetry.
type EventsAPIServer interface {
	Emit(context.Context, *EmitRequest) (*EmitResponse, error)
	mustEmbedUnimplementedEventsAPIServer()
}

// UnimplementedEventsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventsAPIServer struct{}

func (UnimplementedEventsAPIServer) Emit(context.Context, *EmitRequest) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedEventsAPIServer) mustEmbedUnimplementedEventsAPIServer() {}
func (UnimplementedEventsAPIServer) testEmbeddedByValue()                   {}

// UnsafeEventsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsAPIServer will
// result in compilation errors.
type UnsafeEventsAPIServer interface {
	mustEmbedUnimplementedEventsAPIServer()
}

func RegisterEventsAPIServer(s grpc.ServiceRegistrar, srv EventsAPIServer) {
	// If the following call panics, it indicates UnimplementedEventsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventsAPI_ServiceDesc, srv)
}

func _EventsAPI_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsAPIServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsAPI_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsAPIServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventsAPI_ServiceDesc is the grpc.ServiceDesc for EventsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.workerplane.v1.EventsAPI",
	HandlerType: (*EventsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _EventsAPI_Emit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workerplane/v1/workerplane.proto",
}

const (
	ManifestAPI_PublishManifest_FullMethodName = "/graphene.workerplane.v1.ManifestAPI/PublishManifest"
	ManifestAPI_GetPipeline_FullMethodName     = "/graphene.workerplane.v1.ManifestAPI/GetPipeline"
)

// ManifestAPIClient is the client API for ManifestAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManifestAPI records what a pipeline binary IS: published on every
// worker start and on every push, deduplicated by content server-side.
type ManifestAPIClient interface {
	PublishManifest(ctx context.Context, in *PublishManifestRequest, opts ...grpc.CallOption) (*PublishManifestResponse, error)
	// GetPipeline reads the pipeline record: the current image and the
	// last published manifest. A push compares its image against this to
	// skip an unchanged publication.
	GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*GetPipelineResponse, error)
}

type manifestAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewManifestAPIClient(cc grpc.ClientConnInterface) ManifestAPIClient {
	return &manifestAPIClient{cc}
}

func (c *manifestAPIClient) PublishManifest(ctx context.Context, in *PublishManifestRequest, opts ...grpc.CallOption) (*PublishManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishManifestResponse)
	err := c.cc.Invoke(ctx, ManifestAPI_PublishManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestAPIClient) GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*GetPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineResponse)
	err := c.cc.Invoke(ctx, ManifestAPI_GetPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManifestAPIServer is the server API for ManifestAPI service.
// All implementations must embed UnimplementedManifestAPIServer
// for forward compatibility.
//
// ManifestAPI records what a pipeline binary IS: published on every
// worker start and on every push, deduplicated by content server-side.
type ManifestAPIServer interface {
	PublishManifest(context.Context, *PublishManifestRequest) (*PublishManifestResponse, error)
	// GetPipeline reads the pipeline record: the current image and the
	// last published manifest. A push compares its image against this to
	// skip an unchanged publication.
	GetPipeline(context.Context, *GetPipelineRequest) (*GetPipelineResponse, error)
	mustEmbedUnimplementedManifestAPIServer()
}

// UnimplementedManifestAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManifestAPIServer struct{}

func (UnimplementedManifestAPIServer) PublishManifest(context.Context, *PublishManifestRequest) (*PublishManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishManifest not implemented")
}
func (UnimplementedManifestAPIServer) GetPipeline(context.Context, *GetPipelineRequest) (*GetPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipeline not implemented")
}
func (UnimplementedManifestAPIServer) mustEmbedUnimplementedManifestAPIServer() {}
func (UnimplementedManifestAPIServer) testEmbeddedByValue()                     {}

// UnsafeManifestAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManifestAPIServer will
// result in compilation errors.
type UnsafeManifestAPIServer interface {
	mustEmbedUnimplementedManifestAPIServer()
}

func RegisterManifestAPIServer(s grpc.ServiceRegistrar, srv ManifestAPIServer) {
	// If the following call panics, it indicates UnimplementedManifestAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManifestAPI_ServiceDesc, srv)
}

func _ManifestAPI_PublishManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestAPIServer).PublishManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestAPI_PublishManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestAPIServer).PublishManifest(ctx, req.(*PublishManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManifestAPI_GetPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestAPIServer).GetPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestAPI_GetPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestAPIServer).GetPipeline(ctx, req.(*GetPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManifestAPI_ServiceDesc is the grpc.ServiceDesc for ManifestAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManifestAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.workerplane.v1.ManifestAPI",
	HandlerType: (*ManifestAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishManifest",
			Handler:    _ManifestAPI_PublishManifest_Handler,
		},
		{
			MethodName: "GetPipeline",
			Handler:    _ManifestAPI_GetPipeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workerplane/v1/workerplane.proto",
}

const (
	RunsAPI_StartRun_FullMethodName  = "/graphene.workerplane.v1.RunsAPI/StartRun"
	RunsAPI_GetRun_FullMethodName    = "/graphene.workerplane.v1.RunsAPI/GetRun"
	RunsAPI_RunResult_FullMethodName = "/graphene.workerplane.v1.RunsAPI/RunResult"
)

// RunsAPIClient is the client API for RunsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunsAPI starts and observes runs of THIS pipeline from its own
// binary — the `run` subcommand. The management plane serves operators;
// this door serves the user code itself, with the same run token that
// authenticates the rest of the worker plane.
type RunsAPIClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error)
	// RunResult waits for the run to finish and returns its typed result
	// as JSON.
	RunResult(ctx context.Context, in *RunResultRequest, opts ...grpc.CallOption) (*RunResultResponse, error)
}

type runsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewRunsAPIClient(cc grpc.ClientConnInterface) RunsAPIClient {
	return &runsAPIClient{cc}
}

func (c *runsAPIClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunResponse)
	err := c.cc.Invoke(ctx, RunsAPI_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runsAPIClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunResponse)
	err := c.cc.Invoke(ctx, RunsAPI_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runsAPIClient) RunResult(ctx context.Context, in *RunResultRequest, opts ...grpc.CallOption) (*RunResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResultResponse)
	err := c.cc.Invoke(ctx, RunsAPI_RunResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunsAPIServer is the server API for RunsAPI service.
// All implementations must embed UnimplementedRunsAPIServer
// for forward compatibility.
//
// RunsAPI starts and observes runs of THIS pipeline from its own
// binary — the `run` subcommand. The management plane serves operators;
// this door serves the user code itself, with the same run token that
// authenticates the rest of the worker plane.
type RunsAPIServer interface {
	StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error)
	GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error)
	// RunResult waits for the run to finish and returns its typed result
	// as JSON.
	RunResult(context.Context, *RunResultRequest) (*RunResultResponse, error)
	mustEmbedUnimplementedRunsAPIServer()
}

// UnimplementedRunsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunsAPIServer struct{}

func (UnimplementedRunsAPIServer) StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedRunsAPIServer) GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedRunsAPIServer) RunResult(context.Context, *RunResultRequest) (*RunResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunResult not implemented")
}
func (UnimplementedRunsAPIServer) mustEmbedUnimplementedRunsAPIServer() {}
func (UnimplementedRunsAPIServer) testEmbeddedByValue()                 {}

// UnsafeRunsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunsAPIServer will
// result in compilation errors.
type UnsafeRunsAPIServer interface {
	mustEmbedUnimplementedRunsAPIServer()
}

func RegisterRunsAPIServer(s grpc.ServiceRegistrar, srv RunsAPIServer) {
	// If the following call panics, it indicates UnimplementedRunsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunsAPI_ServiceDesc, srv)
}

func _RunsAPI_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsAPIServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsAPI_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsAPIServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunsAPI_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsAPIServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsAPI_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsAPIServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunsAPI_RunResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsAPIServer).RunResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsAPI_RunResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsAPIServer).RunResult(ctx, req.(*RunResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunsAPI_ServiceDesc is the grpc.ServiceDesc for RunsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.workerplane.v1.RunsAPI",
	HandlerType: (*RunsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _RunsAPI_StartRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _RunsAPI_GetRun_Handler,
		},
		{
			MethodName: "RunResult",
			Handler:    _RunsAPI_RunResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workerplane/v1/workerplane.proto",
}
