// Worker plane: what the RUNNING USER CODE calls — secrets at the point
// of use, capabilities from where they were installed, blob bytes. The
// namespace comes from the worker's token; a worker cannot ask for
// another namespace's anything. The contract lives in the pipeline
// repository — the worker side owns it; the server imports and serves.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/workerplane/v1/workerplane.proto

package workerplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version is informative; matching is by label equality only.
	Version string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Labels  map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// BroughtBy is free text: an installer, a person, an image.
	BroughtBy     string `protobuf:"bytes,4,opt,name=brought_by,json=broughtBy,proto3" json:"brought_by,omitempty"`
	Ready         bool   `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{2}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capability) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Capability) GetBroughtBy() string {
	if x != nil {
		return x.BroughtBy
	}
	return ""
}

func (x *Capability) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type PublishCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capability    *Capability            `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCapabilityRequest) Reset() {
	*x = PublishCapabilityRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCapabilityRequest) ProtoMessage() {}

func (x *PublishCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCapabilityRequest.ProtoReflect.Descriptor instead.
func (*PublishCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{3}
}

func (x *PublishCapabilityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PublishCapabilityRequest) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type PublishCapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCapabilityResponse) Reset() {
	*x = PublishCapabilityResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCapabilityResponse) ProtoMessage() {}

func (x *PublishCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCapabilityResponse.ProtoReflect.Descriptor instead.
func (*PublishCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{4}
}

type PutBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunks of the blob, in order.
	Chunk         []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobRequest) Reset() {
	*x = PutBlobRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobRequest) ProtoMessage() {}

func (x *PutBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobRequest.ProtoReflect.Descriptor instead.
func (*PutBlobRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{5}
}

func (x *PutBlobRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutBlobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest is "sha256:<hex>"; Location addresses the bytes in the store.
	Digest        string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Location      string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Size          int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobResponse) Reset() {
	*x = PutBlobResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobResponse) ProtoMessage() {}

func (x *PutBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobResponse.ProtoReflect.Descriptor instead.
func (*PutBlobResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{6}
}

func (x *PutBlobResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PutBlobResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PutBlobResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRequest) Reset() {
	*x = GetBlobRequest{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRequest) ProtoMessage() {}

func (x *GetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRequest) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlobRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GetBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobResponse) Reset() {
	*x = GetBlobResponse{}
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobResponse) ProtoMessage() {}

func (x *GetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workerplane_v1_workerplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobResponse.ProtoReflect.Descriptor instead.
func (*GetBlobResponse) Descriptor() ([]byte, []int) {
	return file_proto_workerplane_v1_workerplane_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlobResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_proto_workerplane_v1_workerplane_proto protoreflect.FileDescriptor

const file_proto_workerplane_v1_workerplane_proto_rawDesc = "" +
	"\n" +
	"&proto/workerplane/v1/workerplane.proto\x12\x17graphene.workerplane.v1\"&\n" +
	"\x10GetSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x11GetSecretResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xf3\x01\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12G\n" +
	"\x06labels\x18\x03 \x03(\v2/.graphene.workerplane.v1.Capability.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"brought_by\x18\x04 \x01(\tR\tbroughtBy\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x18PublishCapabilityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12C\n" +
	"\n" +
	"capability\x18\x02 \x01(\v2#.graphene.workerplane.v1.CapabilityR\n" +
	"capability\"\x1b\n" +
	"\x19PublishCapabilityResponse\"&\n" +
	"\x0ePutBlobRequest\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"Y\n" +
	"\x0fPutBlobResponse\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\",\n" +
	"\x0eGetBlobRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"'\n" +
	"\x0fGetBlobResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2p\n" +
	"\n" +
	"SecretsAPI\x12b\n" +
	"\tGetSecret\x12).graphene.workerplane.v1.GetSecretRequest\x1a*.graphene.workerplane.v1.GetSecretResponse2\x8d\x01\n" +
	"\x0fCapabilitiesAPI\x12z\n" +
	"\x11PublishCapability\x121.graphene.workerplane.v1.PublishCapabilityRequest\x1a2.graphene.workerplane.v1.PublishCapabilityResponse2\xca\x01\n" +
	"\bBlobsAPI\x12^\n" +
	"\aPutBlob\x12'.graphene.workerplane.v1.PutBlobRequest\x1a(.graphene.workerplane.v1.PutBlobResponse(\x01\x12^\n" +
	"\aGetBlob\x12'.graphene.workerplane.v1.GetBlobRequest\x1a(.graphene.workerplane.v1.GetBlobResponse0\x01BHZFgithub.com/graphene-ci/pipeline/pkg/proto/workerplane/v1;workerplanev1b\x06proto3"

var (
	file_proto_workerplane_v1_workerplane_proto_rawDescOnce sync.Once
	file_proto_workerplane_v1_workerplane_proto_rawDescData []byte
)

func file_proto_workerplane_v1_workerplane_proto_rawDescGZIP() []byte {
	file_proto_workerplane_v1_workerplane_proto_rawDescOnce.Do(func() {
		file_proto_workerplane_v1_workerplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workerplane_v1_workerplane_proto_rawDesc), len(file_proto_workerplane_v1_workerplane_proto_rawDesc)))
	})
	return file_proto_workerplane_v1_workerplane_proto_rawDescData
}

var file_proto_workerplane_v1_workerplane_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_workerplane_v1_workerplane_proto_goTypes = []any{
	(*GetSecretRequest)(nil),          // 0: graphene.workerplane.v1.GetSecretRequest
	(*GetSecretResponse)(nil),         // 1: graphene.workerplane.v1.GetSecretResponse
	(*Capability)(nil),                // 2: graphene.workerplane.v1.Capability
	(*PublishCapabilityRequest)(nil),  // 3: graphene.workerplane.v1.PublishCapabilityRequest
	(*PublishCapabilityResponse)(nil), // 4: graphene.workerplane.v1.PublishCapabilityResponse
	(*PutBlobRequest)(nil),            // 5: graphene.workerplane.v1.PutBlobRequest
	(*PutBlobResponse)(nil),           // 6: graphene.workerplane.v1.PutBlobResponse
	(*GetBlobRequest)(nil),            // 7: graphene.workerplane.v1.GetBlobRequest
	(*GetBlobResponse)(nil),           // 8: graphene.workerplane.v1.GetBlobResponse
	nil,                               // 9: graphene.workerplane.v1.Capability.LabelsEntry
}
var file_proto_workerplane_v1_workerplane_proto_depIdxs = []int32{
	9, // 0: graphene.workerplane.v1.Capability.labels:type_name -> graphene.workerplane.v1.Capability.LabelsEntry
	2, // 1: graphene.workerplane.v1.PublishCapabilityRequest.capability:type_name -> graphene.workerplane.v1.Capability
	0, // 2: graphene.workerplane.v1.SecretsAPI.GetSecret:input_type -> graphene.workerplane.v1.GetSecretRequest
	3, // 3: graphene.workerplane.v1.CapabilitiesAPI.PublishCapability:input_type -> graphene.workerplane.v1.PublishCapabilityRequest
	5, // 4: graphene.workerplane.v1.BlobsAPI.PutBlob:input_type -> graphene.workerplane.v1.PutBlobRequest
	7, // 5: graphene.workerplane.v1.BlobsAPI.GetBlob:input_type -> graphene.workerplane.v1.GetBlobRequest
	1, // 6: graphene.workerplane.v1.SecretsAPI.GetSecret:output_type -> graphene.workerplane.v1.GetSecretResponse
	4, // 7: graphene.workerplane.v1.CapabilitiesAPI.PublishCapability:output_type -> graphene.workerplane.v1.PublishCapabilityResponse
	6, // 8: graphene.workerplane.v1.BlobsAPI.PutBlob:output_type -> graphene.workerplane.v1.PutBlobResponse
	8, // 9: graphene.workerplane.v1.BlobsAPI.GetBlob:output_type -> graphene.workerplane.v1.GetBlobResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_workerplane_v1_workerplane_proto_init() }
func file_proto_workerplane_v1_workerplane_proto_init() {
	if File_proto_workerplane_v1_workerplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workerplane_v1_workerplane_proto_rawDesc), len(file_proto_workerplane_v1_workerplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_workerplane_v1_workerplane_proto_goTypes,
		DependencyIndexes: file_proto_workerplane_v1_workerplane_proto_depIdxs,
		MessageInfos:      file_proto_workerplane_v1_workerplane_proto_msgTypes,
	}.Build()
	File_proto_workerplane_v1_workerplane_proto = out.File
	file_proto_workerplane_v1_workerplane_proto_goTypes = nil
	file_proto_workerplane_v1_workerplane_proto_depIdxs = nil
}
